// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static bool get isConfigured {
    try {
      return _hasRequiredValues(currentPlatform);
    } on UnsupportedError {
      return false;
    }
  }

  static bool _hasRequiredValues(FirebaseOptions options) {
    final requiredValues = <String>[
      options.apiKey,
      options.appId,
      options.messagingSenderId,
      options.projectId,
    ];

    if (kIsWeb) {
      requiredValues.add(options.authDomain ?? '');
    }

    return requiredValues.every(
      (value) => value.isNotEmpty && !value.startsWith('YOUR_'),
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RUXvlkSr-LUO-tGvLfFw3p9ARsAbILs',
    appId: '1:551373407898:web:1260736eed7605bf060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    authDomain: 'coffee-system-f7757.firebaseapp.com',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
    measurementId: 'G-LRYQWBBLKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tspMaGl9AgZaiRGYQHMLT983ClMQh1U',
    appId: '1:551373407898:android:5b8843be931f7a94060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcL0mc5r2aiArplQOJTH38x3Zvw4hoMPE',
    appId: '1:551373407898:ios:f3097a8384276157060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
    iosBundleId: 'com.example.coffeeadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
    iosBundleId: 'com.example.coffee_admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5RUXvlkSr-LUO-tGvLfFw3p9ARsAbILs',
    appId: '1:551373407898:web:4011f90d9b7ee242060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    authDomain: 'coffee-system-f7757.firebaseapp.com',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
    measurementId: 'G-FHFYPY7FPJ',
  );

}