// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RUXvlkSr-LUO-tGvLfFw3p9ARsAbILs',
    appId: '1:551373407898:web:1260736eed7605bf060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    authDomain: 'coffee-system-f7757.firebaseapp.com',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
    measurementId: 'G-LRYQWBBLKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tspMaGl9AgZaiRGYQHMLT983ClMQh1U',
    appId: '1:551373407898:android:6b5dfa49fc5597ac060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcL0mc5r2aiArplQOJTH38x3Zvw4hoMPE',
    appId: '1:551373407898:ios:c989ff8c6545c65c060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcL0mc5r2aiArplQOJTH38x3Zvw4hoMPE',
    appId: '1:551373407898:ios:c989ff8c6545c65c060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5RUXvlkSr-LUO-tGvLfFw3p9ARsAbILs',
    appId: '1:551373407898:web:4949eba0b7d5361a060123',
    messagingSenderId: '551373407898',
    projectId: 'coffee-system-f7757',
    authDomain: 'coffee-system-f7757.firebaseapp.com',
    storageBucket: 'coffee-system-f7757.firebasestorage.app',
    measurementId: 'G-R2QGD95ZW3',
  );
}
